# Generated by Django 4.2 on 2023-11-01 23:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_metermodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('manufacturer_date', models.DateField()),
                ('meter_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.metermodel')),
            ],
            options={
                'unique_together': {('number', 'meter_model', 'manufacturer_date')},
            },
        ),
    ]
