# Generated by Django 4.2 on 2023-11-02 00:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_meter'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField()),
                ('account_number', models.IntegerField(unique=True)),
                ('first_name', models.CharField(max_length=50)),
                ('patronymic', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.CharField(blank=True, null=True)),
                ('phone_number', models.IntegerField(null=True)),
                ('verification_code', models.CharField()),
                ('code_validity', models.DateTimeField(default=datetime.datetime(2000, 1, 1, 0, 0))),
            ],
        ),
    ]
