# Generated by Django 4.2 on 2023-11-02 00:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_personalaccount'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstalledMeter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('installation_date', models.DateField()),
                ('remove_date', models.DateField(blank=True, null=True)),
                ('meter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.meter')),
                ('personal_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.personalaccount')),
            ],
            options={
                'unique_together': {('personal_account', 'meter', 'installation_date')},
            },
        ),
    ]
