# Generated by Django 4.2.7 on 2023-11-03 23:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_installedmeter'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeterReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_value', models.IntegerField()),
                ('time_of_taking', models.DateTimeField()),
                ('installed_meter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.installedmeter')),
            ],
            options={
                'unique_together': {('installed_meter', 'current_value', 'time_of_taking')},
            },
        ),
    ]
